language: go

go:
  - 1.7
  - tip

sudo: false

install:
- mkdir $GOPATH/bin && curl https://glide.sh/get | sh

script:
- go test $(glide novendor | grep -v contrib)

services:
- postgresql

addons:
  apt:
    packages:
    - rpm
  postgresql: "9.4"

notifications:
  email: false

matrix:
  allow_failures:
  - go: tip
