# The values specified here are the default values that Clair uses if no configuration file
# is specified or if the keys are not defined.
---
database:
  # PostgreSQL Connection string.
  # Reference: http://www.postgresql.org/docs/9.4/static/libpq-connect.html
  source: 
  # Number of elements to keep in the cache.
  cacheSize: 16384
api:
  # Port on which the main API and the health API will listen on.
  port: 6060
  healthport: 6061
  # Maximum time that API requests may take before they time-out with a HTTP 503 error.
  timeout: 900s
  # Paths to certificates to secure the main API with TLS and client certificate auth.
  cafile:
  keyfile:
  certfile:
updater:
  # Frequency at which the vulnerability updater will run.
  # Use 0 to disable the updater entirely.
  interval: 2h
notifier:
  # Number of attempts that the notifier does when a notification backend fails
  # before it gives up temporarly and try to d
  attempts: 3
  # After a notification has been sent
  renotifyInterval: 2h
  # Configuration for HTTP notifier
  http:
    # Endpoint that will receive notifications with POST requests.
    endpoint:
    # Server name and path to certificates to call the endpoint securely with TLS and client certificate auth.
    servername:
    cafile:
    keyfile:
    certfile:
